server:
  port: 8081
  servlet:
    context-path: /ms
spring:
  profiles:
    active: dev
  # 文件最大
  servlet:
    multipart:
      max-file-size: 50MB
  flyway:
    enabled: true
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db/migration
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
    # 设置总上传数据总大小
    max-request-size: 500MB
  # 将Date转换为long
  jackson:
    serialization:
      write-dates-as-timestamps: true
    date-format: YYYY-MM-DD HH:mm:ss
#驼峰命名转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO

# 系统配置
system:
  config:
    appId: eaf04db0-adef-42a8-bf78-d132a69c3e84
    signingKey: S1n0s0ft.2023.S1n0s0ft.eaf04db0-adef-42a8-bf78-d132a69c3e84